# Generated by Django 3.1 on 2020-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(max_length=200, upload_to='photos/%Y/%m/%d/', verbose_name='изображение'),
        ),
    ]
